name: prueba_pokedex
description: "Prueba Pokedex"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  http: ^1.4.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.0
  flutter_svg: ^2.2.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/pokeball.svg

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/pokeball.png
  android: true
  ios: true
  web: false